### ISSUE TITLE
Data Types

### ISSUE THREAD

**Issue by roblabla** [roblabla/ProtoDef#1]
# Basic types
Those data-types are absolutely necessary for protocols to be remotely useful
- Numeric types : 
  - u8/16/32
  - b8/16/32
  - float
  - double
- Structural types
  - array
  - rest
  - struct
- Conditional types
  - switch

# Extended types
Those are convenience types that are not strictly necessary, but may be useful.
- cstring (NULL-terminated string)
- buffer (same as array, but returns a Buffer instead)
- string (buffer, but runs toString())
- varint (up to 32-bit)
- range

# Custom types
There are two types of custom types
- Function-array custom types : Those use the same creation method as for the basic types : a read, a write, and a sizeOf function. 

- Base-extension custom types : Those are slightly more interesting : they use a basic type, and predefine some of their typeargs.

# Tests
Every built-in types need to be battletested for every expected behaviors.

**Comment by rom1504** [comment]
Tests tracked in #25
The rest is there
