### ISSUE TITLE
Put createPacketBuffer and parsePacketData in ProtoDef class

### ISSUE THREAD

**Issue by rom1504** [roblabla/ProtoDef#21]
Creating a whole packet buffer, or reading one is useful in other contexts than a serializer/a parser.

Having to use proto.read and proto.write is annoying.

Might be a good time to do parsePacketData -> parsePacketBuffer

**Comment by roblabla** [comment]
I'm not sure I agree. ProtoDef currently doesn't know what the top-level type is. Unless we come up with a good way to define this, we currently can't proceed with this.

**Comment by rom1504** [comment]
I meant a function parsePacketBuffer(type,buffer)
