### ISSUE TITLE
Handle partially available data

### ISSUE THREAD

**Issue by rom1504** [roblabla/ProtoDef#24]
We used to return null in readers because the data might be partially available in <=1.6 minecraft version.
If we want to be able to handle these kind of behavior, we might want to throw a special exception in this kind of case, and then handle it properly in the parser. (I guess "wait" for more data and try again)

**Comment by roblabla** [comment]
This needs to be efficient, meaning we don't want to "lose" progress just because we are missing some data. This means we might want to go "continuation-style" (asynchronous `read()` function that returns a byte when it's available).

**Comment by rom1504** [comment]
hmm, seems I do need this for classic.

**Comment by rom1504** [comment]
https://streams.spec.whatwg.org/#example-40fd18cb

**Comment by rom1504** [comment]
What does that mean for readers that themselves call the read method (say containers for example) ? Do they need `this` to be the stream or something similar?

**Comment by roblabla** [comment]
Instead of a buffer,  they'll be passed a stream probably?

**Comment by rom1504** [comment]
Ah yeah that makes sense. 
Here is the implementation of whatwg streams https://www.npmjs.com/package/whatwg-streams
It seems pretty experimental but if it works I'm fine with it.

**Comment by rom1504** [comment]
Hmm actually that thing on npm seems pretty old, we might need to depend on https://github.com/whatwg/streams/tree/master/reference-implementation

**Comment by roblabla** [comment]
Worse case scenario we can just depend on anything that exposes a similar
polling interface,  it doesn't have to be whatwg streams (they are still in
heavy development!). I mostly posted those as an example of what I believed
the interface should look like ;)

**Comment by rom1504** [comment]
Yeah but whatwg streams do seem reasonable, I'll try and see if they can be used.

**Comment by rom1504** [comment]
https://www.npmjs.com/package/pull-stream might be interesting

**Comment by rom1504** [comment]
These libs don't seem quite ready to be used (pull-stream works with callback and whatwg stream is unpublished).
I guess we would have to implement it ourselves ?

**Comment by rom1504** [comment]
https://github.com/whatwg/streams/issues/406#issuecomment-158994868

**Comment by rom1504** [comment]
@roblabla what would that means for write/sizeOf ? no change to their API ?

**Comment by rom1504** [comment]
I'm starting to think it might be more efficient to keep the current sync model and just return null...

**Comment by rom1504** [comment]
I might try again to make that promise thingy to work with nmp.

Maybe I will make an alternative PR with the "throw an error" option though. It sure is a little bit less efficient if lot of packets are cut, but in the general case it's actually very likely more efficient (no async overhead !) and it keeps the API sync which is nice.

**Comment by rom1504** [comment]
closing this, leaving https://github.com/roblabla/ProtoDef/issues/3
It's too inefficient to do it asyncly. We can always reopen later if needed
