### ISSUE TITLE
TestData in json so other language implementation can check with the same tests

### ISSUE THREAD

**Issue by rom1504** [roblabla/ProtoDef#25]
https://github.com/PrismarineJS/prismarine-nbt/blob/master/test/datatypes.js#L14
https://github.com/roblabla/ProtoDef/blob/master/test/dataTypes/numeric.js#L11

Wouldn't it be interesting ?

**Comment by roblabla** [comment]
:+1:

**Comment by rom1504** [comment]
The format must have:
* the name of the type
* an (optional) description for that type
* a list of test values with for that type with:
  * a description for that value
  * the value
  * the expected buffer : can be encoded as an array of string (`["0x01","0x02"]`)

**Comment by rom1504** [comment]
Proposed schema:
```json
[
 {
    "type":"i8",
    "description":"8-bit bytes",
    "data":[
     {
        "description":"readPos",
        "buffer":["0x3d"],
        "value":61
     }
    ]
 }
]
```

**Comment by rom1504** [comment]
Actually I think "an (optional) description for that type" is useless, it should be in the doc.

**Comment by rom1504** [comment]
I used this to convert the data in numeric.js:
```js
function bufferToArray(buffer)
{
  var arr=[];
  for(var i=0;i<buffer.length;i++) {
    var r=buffer[i].toString(16);
    arr.push("0x"+(r.length==2 ? r: "0"+r));
  }
  return arr;
}

require("fs").writeFileSync("numeric.json",JSON.stringify(Object.keys(testData).map(key => ({
  "type":key,
  "values":Object.keys(testData[key]).filter(name => name.indexOf("read")!=-1).map(name => ({
    "description":name=="readPos" ? "positive" : (name=="readNeg" ? "negative" : name),
    "buffer":bufferToArray(testData[key][name]["buffer"]),
    "value":testData[key][name]["value"]
  }))
})),null,2));
```

**Comment by rom1504** [comment]
Oh and the type property is https://github.com/PrismarineJS/minecraft-data/blob/master/schemas/protocol_schema.json#L5 (related to https://github.com/roblabla/ProtoDef/issues/46#issuecomment-186217702 )

**Comment by rom1504** [comment]
hmm no. Let's have typeArgs be an optional property of the test.

**Comment by rom1504** [comment]
going with "subtypes" which contain an array of object with properties
* description
* type
* values

It's either values or subtypes

going to make an actual json schema for this.

**Comment by rom1504** [comment]
done
