### ISSUE TITLE
Packet State

### ISSUE THREAD

**Issue by roblabla** [roblabla/ProtoDef#3]
Current implementation likes to waste cycles to parse stuff to later discard it due to the structure not being complete. It would be nice to add a way for primitives to "save" their work somewhere until more data is available to resume the parsing, thus avoiding waste of cpu cycles.

**Comment by rom1504** [comment]
same as #24

**Comment by rom1504** [comment]
closing as https://github.com/roblabla/ProtoDef/issues/24#issuecomment-185859341
