### ISSUE TITLE
Move uuid and restBuffer here ?

### ISSUE THREAD

**Issue by rom1504** [roblabla/ProtoDef#31]
They are generic types that could be used elsewhere than minecraft. (restBuffer is a bit of a hack, but not really specific to minecraft)

**Comment by roblabla** [comment]
Haven't seen a use for uuid yet outside mc. I think we should try not to bloat the standard types too much.

**Comment by rom1504** [comment]
Well mcpe does use it, but yeah that's still minecraft. Okay.
