### ISSUE TITLE
Include name in type

### ISSUE THREAD

**Issue by roblabla** [roblabla/ProtoDef#4]
Currently, a "type" variable doesn't include a name, which makes type dependency kind of complicated (can't have a type x that requires type y, since it needs to know what name the user will give to type y). To avoid this, we may want to make `createType` and `extendType` take a name parameter, and include it inside the type definition.

Otherwise, we could also include some type of dependency tree for types, but this feels way overkill.

**Comment by rom1504** [comment]
What would be the use of the "dependency" ? Checking we have all the required types ?
That can be done by the "user" (Protodef class) AFAIK

**Comment by rom1504** [comment]
Not sure what this is about, in the mean type, closing.

**Comment by roblabla** [comment]
This is necessary for automatic discovery of datatype deps. E. G.
proto.autoRequire() would add the missing types by finding them.

But I'm not sure it was a good idea to start with. Let's keep the magic to
a minimum ^^.
