### ISSUE TITLE
Add all tests

### ISSUE THREAD

**Issue by rom1504** [roblabla/ProtoDef#56]
* utils
 * [x] varint #53 
 * [x] bool
 * [x] pstring
 * [x] buffer
 * [x] void
 * [x] bitfield
 * [x] cstring
 * [x] mapper
* numeric
 * [x] i8
 * [x] u8
 * [x] i16
 * [x] u16
 * [x] i32
 * [x] u32
 * [x] f32
 * [x] f64
 * [x] i64
* conditional
 * [x] switch
 * [x] option
* structures
 * [x] array
 * [x] count
 * [x] container

**Comment by rom1504** [comment]
@roblabla Did you ever tried cstring ? I tried adding a test for it and it looks like it's broken

**Comment by roblabla** [comment]
No, i don't remember ever testing it.

**Comment by rom1504** [comment]
count test would be a container containing both a count and an array using that count.

**Comment by rom1504** [comment]
done !
