### ISSUE TITLE
Unique name

### ISSUE THREAD

**Issue by rom1504** [roblabla/ProtoDef#9]
https://www.npmjs.com/package/protocol
https://www.npmjs.com/package/protocols

available:
* protocol-serializer
* generic-protocol

It might also be possible to merge with something else, like https://github.com/codemix/binary-protocol

**Comment by roblabla** [comment]
Fak. I should've parked protocols when it was still available ;( I guess I'll have to think of a good name. Something like protodef ? 

I'm not too willing to merge this into something else, I'd like to keep control over its direction. The only thing that comes somewhat close to what I'd like protocols to be is [packet](https://github.com/bigeasy/packet) : a specification format, a serializer, a deserializer (I wanted to move NMP to packet at one point ;))

**Comment by rom1504** [comment]
Sure, what I meant by "merging" was mostly "ask nicely to take over their name" :p 
But I guess that's not necessarily possible so we might have to find a new name.

About packet : the idea is similar to Protocols, but I looked a bit at their code and I don't like it too much.

**Comment by rom1504** [comment]
done
